name: Publish to npm on merge

on:
  pull_request:
    paths:
      - 'src/'
      - package.json
      - package-lock.json

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Setup NodeJS
      uses: actions/setup-node@v3
      with:
        node-version: 16
        cache: 'npm'
      env:
        NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

    - name: Check if version is published
      id: version-check
      shell: bash
      continue-on-error: true
      run: |
        PACKAGE_VERSION=$(cat ./package.json | jq -r ".version");
        VERSIONS=$(npm view @nathanstilwell/time versions)
        if [[ $VERSIONS == *"$PACKAGE_VERSION"* ]]; then
          echo "published=yes" >> $GITHUB_OUTPUT
          echo
          echo "🛑 Cluster UI package version $PACKAGE_VERSION is already published"
          echo "to npm. Publishing step should be skipped. 🛑"
        else
          echo "published=no" >> $GITHUB_OUTPUT
        fi

    - name: Build
      run: |
        npm install;
        npm run build;

    - name: Publish
      if: steps.version-check.outputs.published == 'no'
      run: |
        npm publish --access public --tag testing --dry-run

